// xiuxian/img/src/component/sky.tsx
import React from 'react'
import { hash } from 'alemonjs'
import { createRequire, BackgroundImage } from 'react-puppeteer'
import { ThemesEmun } from '../core'
const require = createRequire(import.meta.url)

type PropsType = {
  data: {
    id: number
    UID: string
    name: string
    power: number
    autograph: string
    avatar: string
  }[]
  theme?: ThemesEmun
}

export default function App({ data, theme }: PropsType) {
  return (
    <div
      id="root"
      data-theme={theme}
      // style={{ backgroundImage: 'var(--background-image)' }}
    >
      <BackgroundImage
        className="w-full m-auto text-center"
        url={require('../../../../public/img/information.jpg')}
      >
        {data.map((item, index) => (
          <div key={index}>
            <div style={{ display: 'grid' }}>
              <BackgroundImage
                className="user_top"
                size={'100% 100%'}
                url={require('../../../../public/img/left.jpg')}
              >
                <div className="user_top_left">
                  <div
                    className="user_top_right_font0 text-black text-2xl p-3"
                    style={{ padding: '5px' }}
                  >
                    {isNaN(Number(item.UID)) ? hash(item.UID) : item.UID}
                  </div>
                  <div
                    className="user_top_right_font1 text-black text-2xl p-3"
                    style={{ padding: '5px' }}
                  >
                    道号: {item.name}
                  </div>
                  <div
                    className="user_top_right_font2 text-black text-2xl p-3"
                    style={{ padding: '5px' }}
                  >
                    排名: {item.id}
                  </div>
                  <div
                    className="user_top_right_font1 text-black text-2xl p-3"
                    style={{ padding: '5px' }}
                  >
                    战力: {item.power}
                  </div>
                </div>
                <div className="user_top_right">
                  <BackgroundImage
                    className="user_top_img_bottom"
                    size={'100% 100%'}
                    url={require('../../../../public/img/right.jpg')}
                  >
                    <img
                      className="user_top_img"
                      src={item.avatar}
                      alt="User Avatar"
                    />
                  </BackgroundImage>
                </div>
              </BackgroundImage>
            </div>
            <div className="rounded-lg w-full">
              <div className="pb-5">
                <div className="user_top_right_font0 text-black text-2xl p-3">
                  {'[修心道宣]'}
                </div>
                <div className="user_top_right_font2 text-black text-2xl p-3">
                  {item.autograph}
                </div>
              </div>
            </div>
          </div>
        ))}
      </BackgroundImage>
    </div>
  )
}

// public/pages/sky.vue
<script>
  Vue.createApp({
    setup: () => ({
      data: BOT_DATA
    })
  }).mount('#app')
</script>

<template>
  <div id="app" class="user">
    <div v-for="item of data">
      <div style="display: grid">
        <div class="user_top">
          <div class="user_top_left">
            <div
              class="user_top_right_font0 font_control Horizontal_grid"
              style="padding: 5px"
            >
              {{ item.uid }}
            </div>
            <div
              class="user_top_right_font1 font_control Horizontal_grid"
              style="padding: 5px"
            >
              道号:{{ item.name }}
            </div>
            <div
              class="user_top_right_font2 font_control Horizontal_grid"
              style="padding: 5px"
            >
              排名:{{ item.id }}
            </div>
            <div
              class="user_top_right_font1 font_control Horizontal_grid"
              style="padding: 5px"
            >
              战力:{{ item.power }}
            </div>
          </div>
          <div class="user_top_right">
            <div class="user_top_img_bottom">
              <img class="user_top_img" :src="item.avatar" />
            </div>
          </div>
        </div>
      </div>

      <div class="user_bottom1">
        <div class="use_data">
          <div class="user_top_right_font0 font_control Horizontal_grid">
            [修心道宣]
          </div>
          <div class="user_top_right_font2 font_control Horizontal_grid">
            {{ item.autograph }}
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<head>
  <link rel="stylesheet" href="@/css/sky.css">
</head>

<style>
  .user {
    background-image: url('@/img/user/information/information.jpg');
  }

  .user_top {
    background-image: url('@/img/user/information/left.jpg');
  }

  .user_top_img_bottom {
    background-image: url('@/img/user/information/right.jpg');
  }
</style>
